### ISSUE TITLE
Where do proposals go?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#3]
"The group publishes an index of the proposals worked on in GitHub." do you know where this is going to be or not?
it points to https://example.com/indexpage at the moment

**Comment by darobin** [comment]
One thing I can do is that I can reuse the code that now powers specs.webplatform.org. Either we can use that URL, or we can set it up to work for specs.wicg.io (or whatever).

The system has some nice features. One is that it centralises drafts so they don't get lost everywhere in GH pages; another is that it allows to publish from arbitrary branches, not just gh-pages, so that you can have alternative proposals inside the same repo. When using ReSpec (which is recommended there) it also generates a static version, which is nicer for search engines, load time, etc.

I can also change it to key off the repos that are managed under https://labs.w3.org/hatchery/ash-nazg/. This means that as soon as you register a repo for your contributions to go to the CG, things get picked up on the index.

**Comment by marcoscaceres** [comment]
Alternative is to just do what TC-39 does (proposals in the README):
 https://github.com/tc39/ecma262

**Comment by jonathanKingston** [comment]
So I was speaking to @slightlyoff earlier today.

It would be nice if the first steps in making a proposal was more a document of words and code rather than formal spec themselves. The specs can come second to a well structured document being supportive to the use cases and also example syntax, how to test, what the problem areas of implementing might be, who needs to be involved.

Designing to the constraints of formalised documents then likely will not be accepting to new ideas as much as rougher talks up front. Rust and Ember RFC process seems to match this a little closer perhaps.

**Comment by marcoscaceres** [comment]
@jonathanKingston, created https://github.com/WICG/admin/issues/10
