### ISSUE TITLE
TPAC 2019 Draft Agenda

### ISSUE THREAD

**Issue by travisleithead** [WICG/admin#78]
Supposing this is as good a place as any to track an agenda!

Hey Incubators! [W3C TPAC](https://www.w3.org/2019/09/TPAC/) is nearly upon us! For those of you who will be attending this year, our little community group has an opportunity to host topics related to the various current (and prospective!) incubations on [Thursday](https://www.w3.org/2019/09/TPAC/schedule.html#cgs-thu) and [Friday](https://www.w3.org/2019/09/TPAC/schedule.html#cgs-fri). To help us get organized in advance, we can use this issue as a call for agenda topics, and to sort and organize the topics you folks would like to discuss.

As you suggest a topic, please include the following:
* the topic :-)
* who should lead the discussion
* hoped for outcome of the discussion
* a rough-idea of how long the discussion should be

We currently have 2 hours on 2 days to pack as much discussion-goodness as possible! 

Remote participation - [link](https://meet.google.com/dhp-irus-ghx)
**The session will be recorded.**

## Thursday (08:30 - 10:30) -
Meeting Location: Hishi, 3F (Maximum attendance: 20)

* Topic: WebTransport - 30 mins
* Topic: WebCodecs - 30 mins

## Friday (10:30 - 12:30)

* Topic: TAG and incubation - 60 mins
 * Topic: Best practices for complex incubation projects - 60 mins

**Comment by pthatcherg** [comment]
Topic: WebTransport
Leading: Peter Thatcher
Hoped outcome: Everyone knows what WebTransport is; everyone knows what the status of WebTransport is; we all know what the next steps are (esp. with regards to IETF coordination); we have figured out solutions to some advanced design topics like stream prioritization, congestion control, and multiplexing; all the browser vendors are excited to implement it; and many (all?) web developers are excited to use it.
Rough idea of length: 30 min

**Comment by pthatcherg** [comment]
Topic: WebCodecs
Leading: Peter Thatcher
Hoped outcome: Everyone knows what WebCodecs is and its status; we have figured out solutions to some advanced design topics like capabilities and efficient handling of media in wasm; all the browser vendors are excited to implement it; and many web developers are excited to use it.
Rough idea of length: 30 min

**Comment by marcoscaceres** [comment]
@pthatcherg, thanks... do you have a preference for which day? Also, anyone you'd like to see there?

**Comment by pthatcherg** [comment]
I would prefer Thursday, but either day works.

**Comment by alice** [comment]
TAG would like to visit at 10:30 on Friday to chat about TAG review process and incubation.

@yoavweiss proposed the following topics as a starting point:
> When would the TAG like incubations to file for reviews? Is there any process WICG can put in place to improve that process and help reduce its latencies?
Talking to Kenneth a few months back we talked about e.g. badging proposals with their "phase"
similarly, we could have different urgency labels that can help you prioritize the urgent stuff

**Comment by marcoscaceres** [comment]
Excellent, see you Friday.

**Comment by heycam** [comment]
Topic: https://github.com/WICG/construct-stylesheets/issues/45
Leading: I guess I can but I'm not officially a WICG member; would prefer to defer to a spec author
Hoped for outcome: Agreement on what API to use for `adoptedStyleSheets`
Rough idea of length: 30 minutes

Also happy to discuss other issues on this spec during this time.

/cc @rakina @emilio @rniwa @domenic

**Comment by heycam** [comment]
Would prefer Thursday for that topic.

**Comment by rniwa** [comment]
@heycam : adoptedStyleSheets is listed as a topic on Tue session for web components: https://github.com/w3c/webcomponents/issues/826

**Comment by heycam** [comment]
@rniwa thanks, didn't realise that. Happy to discuss it there instead.

**Comment by adrianhopebailie** [comment]
We're discussing [Web Monetization](https://discourse.wicg.io/t/proposal-web-monetization-a-new-revenue-model-for-the-web/3785) in the [Web Payments WG on Tuesday](https://github.com/w3c/webpayments/wiki/FTF-Agenda-201909#17-september)

**Comment by lennart-csio** [comment]
will there be a live stream or recording?

**Comment by AmeliaBR** [comment]
Sorry for the late notice, but if there's still room on Friday I'd like to follow up the TAG & incubation discussion with a broader discussion on incubation, specifically for larger, more complex proposals.

By complex proposals, I mean proposals that involve multiple interacting features that would add considerable new behavior to the web platform. These proposals need more than one-page explainers & probably many stages of review — but are also more work to review! Complex feature proposals have traditionally been developed, with more or less success, in non-WICG community groups with a dedicated community of subject matter experts.

As an example: I've been working this year with the Maps for HTML community group (who are meeting earlier Friday morning in the CG room). Their proposal has had considerable investment from the geospatial community, but the guidance they've been following from the web side (go build a custom element, get people using it, then the browsers might listen to you) has probably resulted in work that will need to be torn up and redone because of architecture issues. Which isn't a great way to get community support for a project!

Based on Q&A I caught Tuesday afternoon between @nigelmegitt and @cwilso, I think other subject-matter community groups are also a little frustrated that they are being left of the discussion & feedback from the standards/implementer community that is happening with WICG. I know I've also had some concerns that the new SVG CG is isolated from WICG, even though there were good reasons to create a separate group.

Topic: Best practices for complex incubation projects

Lead: Amelia Bellamy-Royds (Chair, SVG Community Group / Co-chair, Maps for HTML Community Group)

Desired outcomes:

- Some agreement/clarity on how WICG should be coordinating with or supporting other CG that are incubating specifications.
- Specific guidance (or plans to develop it) for the milestones and deliverables that complex proposals should follow (e.g., use cases & requirements reviews, draft specifications with tests, polyfill implementations…).
- Guidance on when CG projects should be applying for W3C horizontal reviews, and what they need to do to prepare for those reviews.

Time: 30-60 minutes, probably flowing naturally from the TAG incubation discussion

**Comment by yoavweiss** [comment]
@ameliaBR - SGTM! :)

**Comment by yoavweiss** [comment]
@lennart-csio I'll set up remote participation and session recording

**Comment by lennart-csio** [comment]
@yoavweiss thanks a lot! :)

**Comment by michaelwasserman** [comment]
Modified request: If there's time on Friday, I'd like to give a 2-minute overview of problems and use cases I'm exploring around [Screen Enumeration](https://github.com/spark008/screen-enumeration/blob/master/EXPLAINER.md) and [Window Placement](https://github.com/spark008/window-placement/blob/master/EXPLAINER.md).

I'm new to W3C and the web platform, and I'd like to hear from WICG folks how this work might align with working groups' interest areas and how the incubation process applies to ideas like this.

Abstract: As computing devices more commonly support and use multiple displays, it becomes
more important to give web developers the right tools to present their content
across the set of connected displays.

Discourse (with old explainer text): https://discourse.wicg.io/t/proposal-screen-enumeration-api/3861

**Comment by yoavweiss** [comment]
@michaelwasserman - seems like our agenda for today is rather full already, but feel free to come to the meeting. If we'll have time, we'd discuss this as a group, and if not, I'm happy to chat about it afterwards :)

**Comment by lennart-csio** [comment]
@yoavweiss was this session recorded? could you send me a link? thanks :)

**Comment by yoavweiss** [comment]
@lennart-csio - unfortunately, we were able to record only the [WebTransport session](https://youtu.be/eqiz6ZHqT4w). Hope that helps! :)

**Comment by travisleithead** [comment]
I'd like to close this issue, but we first need to get the IRC log posted somewhere public...

**Comment by marcoscaceres** [comment]
If we have a link, maybe best to just send them the the public wicg list and www-archive?

**Comment by yoavweiss** [comment]
The link from IRC is a 404.

I manually created minutes docs:
* [TAG discussion](https://docs.google.com/document/d/1hPaEUaH1djp2w-A4FzMUEiylxbxHM3gvg1lUF7Tm46Q/edit#heading=h.y063ezn9y8y5)
* [Complex Incubations](https://docs.google.com/document/d/1L36EhPaEQ0d9k_nGBiqJDryrgqqM3eGPlBgB6PsDpgQ/edit?usp=sharing)

**Comment by yoavweiss** [comment]
Also [sent](https://lists.w3.org/Archives/Public/public-wicg/2019Sep/0002.html) to public-wicg for archiving purposes. Closing
